import { z } from 'zod'

// Dev-only fallbacks. In production these must be overridden with real secrets,
// or the app refuses to boot (see the superRefine below) — otherwise anyone
// could forge a session cookie against the hard-coded, source-visible HMAC key.
const DEV_PASSWORD = 'papertrack'
const DEV_SECRET = 'dev-insecure-secret-change-me'

const schema = z
  .object({
    DATABASE_URL: z.string().min(1, 'DATABASE_URL is required'),
    PORT: z.coerce.number().default(3100),
    NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
    APP_PASSWORD: z.string().default(DEV_PASSWORD),
    SESSION_SECRET: z.string().min(1).default(DEV_SECRET),
    WEB_ORIGIN: z.string().default('http://localhost:5174'),
    STORAGE_LOCAL_DIR: z.string().default('./storage-data'),
    R2_ACCOUNT_ID: z.string().default(''),
    R2_ACCESS_KEY_ID: z.string().default(''),
    R2_SECRET_ACCESS_KEY: z.string().default(''),
    R2_BUCKET: z.string().default('papertrack'),
    R2_PUBLIC_BASE_URL: z.string().default(''),
    // AI (optional). A personal Claude Code OAuth token (from `claude setup-token`).
    // Present → the dashboard note is generated by Claude, grounded in the
    // computed signals; absent → the deterministic nudge. Used as an OAuth bearer
    // token, not an API key — so no metered API billing, just the subscription.
    CLAUDE_CODE_OAUTH_TOKEN: z.string().default(''),
    AI_MODEL: z.string().default('claude-haiku-4-5'),
  })
  .superRefine((val, ctx) => {
    if (val.NODE_ENV !== 'production') return
    if (val.SESSION_SECRET === DEV_SECRET || val.SESSION_SECRET.length < 16) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['SESSION_SECRET'],
        message: 'SESSION_SECRET must be a strong (≥16 char) non-default value in production',
      })
    }
    if (val.APP_PASSWORD === DEV_PASSWORD) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['APP_PASSWORD'],
        message: 'APP_PASSWORD must be set to a non-default value in production',
      })
    }
  })

const parsed = schema.safeParse(process.env)
if (!parsed.success) {
  console.error('✗ Invalid environment:', parsed.error.flatten().fieldErrors)
  process.exit(1)
}

export const env = parsed.data
export const isProd = env.NODE_ENV === 'production'

/** R2 is used only when all four core credentials are present; else local disk. */
export const useR2 = Boolean(
  env.R2_ACCOUNT_ID && env.R2_ACCESS_KEY_ID && env.R2_SECRET_ACCESS_KEY && env.R2_BUCKET,
)

/** AI features light up only when an OAuth token is present; else deterministic fallback. */
export const useAI = Boolean(env.CLAUDE_CODE_OAUTH_TOKEN)
